-- Remove 1px border around hyprshot screenshots
-- Disable animation for the hyprshot selection overlay
-- hl.layer_rule({
--     name  = "hyprshot-no-anim",
--     match = { namespace = "^selection$" },
--     no_anim = true,
-- })
